=== api-evangelist/booking-holdings/json-schema/demand-api-flights-output-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/booking-holdings/refs/heads/main/json-schema/demand-api-flights-output-schema.json",
  "title": "FlightsOutput",
  "description": "FlightsOutput schema from Booking.com Demand API",
  "type": "object",
  "properties": {
    "id": {
      "description": "Order id",
      "type": "string"
    },
    "reservation": {
      "description": "This is the reservation id for the travel service in this order.",
      "type": "string"
    },
    "currency": {
      "type": "object",
      "properties": {
        "booker_currency": {
          "description": "The currency of the booker.",
          "type": "string"
        },
        "order_currency": {
          "description": "The currency in which the order was created.",
          "type": "string"
        }
      }
    },
    "itineraries": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "arrival": {
            "description": "Arrival itinerary.",
            "type": "object",
            "properties": {
              "airport": {
                "description": "A three-letter code that uniquely identifies an airport as defined by the International Air Transport Association (IATA). The full list can be obtained by calling  [common/locations/airports](#/common/locations/airports).",
                "pattern": "^[A-Z]{3}$",
                "type": "string"
              },
              "date_time": {
                "description": "Date time of the itinerary.",
                "type": "string",
                "format": "date-time"
              }
            }
          },
          "departure": {
            "description": "Departure itinerary.",
            "type": "object",
            "properties": {
              "airport": {
                "description": "A three-letter code that uniquely identifies an airport as defined by the International Air Transport Association (IATA). The full list can be obtained by calling  [common/locations/airports](#/common/locations/airports).",
                "pattern": "^[A-Z]{3}$",
                "type": "string"
              },
              "date_time": {
                "description": "Date time of the itinerary.",
                "type": "string",
                "format": "date-time"
              }
            }
          }
        }
      }
    },
    "label": {
      "description": "Identifier associated with the order.",
      "type": "string"
    },
    "price": {
      "type": "object",
      "properties": {
        "booker_currency": {
          "description": "The price in the currency of the booker",
          "type": "number",
          "format": "double"
        },
        "order_currency": {
          "description": "The price in the currency in which order was created",
          "type": "number",
          "format": "double"
        }
      }
    },
    "status": {
      "type": "string",
      "enum": [
        "booked",
        "cancelled",
        "unknown"
      ]
    }
  }
}

=== api-evangelist/booking-holdings/examples/demand-api-flights-output-example.json
{
  "id": "10781902",
  "reservation": "string",
  "currency": {
    "booker_currency": "USD",
    "order_currency": "USD"
  },
  "itineraries": [
    {
      "arrival": {},
      "departure": {}
    }
  ],
  "label": "Grand Plaza Hotel",
  "price": {
    "booker_currency": 0.39,
    "order_currency": 12.96
  }
}
